name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          pip3 install pipenv
          yarn install
      - name: setup Bazel configuration
        run: |
          yarn bazelrc:ci
          yarn bazelrc
      - name: compile
        run: yarn build
      - name: unit tests
        run: yarn test
      - name: create bundle
        run: yarn package
      - name: integration tests
        run: yarn integration
