name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Bazel
        uses: actions/cache@v1
        env:
          cache-name: cache-bazelisk
        with:
          path: ~/.cache/bazelisk
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.bazelversion') }}
      - name: Cache Bazel Artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-bazel-artifacts
        with:
          path: ~/bazel_repository_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Cache Python Install
        uses: actions/cache@v1
        env:
          cache-name: cache-pipenv
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: installing dependencies
        run: |
          pip3 install pipenv
          yarn install
      - name: setup Bazel configuration
        run: |
          yarn bazelrc:ci
          yarn bazelrc
      - name: compile
        run: yarn build
      - name: unit tests
        run: yarn test
      - name: create bundle
        run: yarn package
      - name: integration tests
        run: yarn integration
      - uses: actions/upload-artifact@v1
        with:
          name: Bundles
          path: dist
